# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  - master
  - develop

stages:
  - stage: build
    jobs:
      - job: build
        displayName: build
        pool:
          vmImage: "ubuntu-latest"

        variables:
          solution: "**/*.sln"
          buildPlatform: "Any CPU"
          buildConfiguration: "Release"
          buildParameters.RestoreBuildProjects: "**/*.csproj"
          buildParameters.TestProjects: "**/*UnitTests/*.csproj"

        steps:
          - script: echo hi Joe!
            displayName: 'What directory are we in'

  #         - task: DotNetCoreCLI@2
  #           displayName: Restore
  #           inputs:
  #             command: restore
  #             projects: $(buildParameters.RestoreBuildProjects)

  #         - task: DotNetCoreCLI@2
  #           displayName: Build
  #           inputs:
  #             projects: $(buildParameters.RestoreBuildProjects)
  #             arguments: --configuration $(BuildConfiguration)

  #         - task: DotNetCoreCLI@2
  #           displayName: Publish
  #           inputs:
  #             command: publish
  #             publishWebProjects: True
  #             projects: $(buildParameters.RestoreBuildProjects)
  #             arguments: --configuration $(BuildConfiguration) --output $(build.ArtifactStagingDirectory)
  #             zipAfterPublish: True

  #         - task: PublishBuildArtifacts@1
  #           displayName: Publish Artifact
  #           condition: succeededOrFailed()
  #           inputs:
  #             pathtoPublish: $(build.ArtifactStagingDirectory)
  #             targetPath: "drop"

  # - stage: deploy_to_prod
  #   dependsOn: Build
  #   condition: and(always(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  #   jobs:
  #     - job: deployToAppService
  #       displayName: "DeployToAppService - Prod"
  #       steps:
  #         - task: DownloadBuildArtifacts@1
  #           inputs:
  #             buildType: "current"
  #             downloadType: "single"
  #             artifactName: "drop"
  #             downloadPath: "$(System.DefaultWorkingDirectory)"

  #         - task: AzureWebApp@1
  #           inputs:
  #           azureSubscription: "Personal-Sub(1)(57f4859b-8037-4106-ac17-61520b9de19b)"
  #           appType: "webAppLinux"
  #           appName: "entraconnect-dev-api"
  #           package: "$(System.DefaultWorkingDirectory)/**/*.zip"
  #           appSettings: '-ASPNETCORE_ENVIRONMENT "Production"'

