# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  - master
  - develop

resources:
  repositories:
    - repository: sharedTemplates                   # alias you choose
      type: github
      name: joeipe/azure-pipeline-templates
      ref: refs/heads/master
      endpoint: joeipe

stages:
  - template: templates/dotnet-webapp-multistage.yml
    parameters:
      apiName: 'entraconnect'